#!/usr/bin/env bash
# bootstrap-sops-builder.sh
#
# Bootstraps sops-nix + Tailscale auth for the Determinate linux-builder VM:
#   1. Provisions an age key at ~/.config/sops/age/keys.txt (standard sops
#      CLI lookup path, outside the dotfiles repo).
#   2. Writes ~/.config/lockbox-home/.sops.yaml with that recipient.
#   3. Prompts for a Tailscale pre-auth key and an it-admin password,
#      hashes the password with mkpasswd, and encrypts both into
#      ~/.config/lockbox-home/secrets.yaml via sops.
#   4. Updates the flake lock for sops-nix.
#   5. darwin-rebuild switch --impure (the VM config references the age
#      key by absolute path outside the flake, requiring impure eval).
#   6. Restarts the linux-builder VM and verifies cache reachability.
#
# Idempotent: existing age key / .sops.yaml / secrets.yaml are reused unless
# --force is passed. Re-running after a key rotation requires --force.
# Empty / non-sops-formatted secrets.yaml files are regenerated automatically.
#
# Requires: nix (Determinate), darwin-rebuild, sudo.

set -euo pipefail

REPO="${HOME}/.config/lockbox-home"
# Age key lives at the standard sops CLI lookup path, OUTSIDE the dotfiles
# repo. darwin-rebuild runs with --impure so Nix can import the absolute
# path into /nix/store. Trade-off: the rebuild for this host is impure,
# but no secret material (encrypted or otherwise) sits in the repo.
AGE_DIR="${HOME}/.config/sops/age"
AGE_KEY="${AGE_DIR}/keys.txt"
SOPS_POLICY="${REPO}/.sops.yaml"
SECRETS_FILE="${REPO}/secrets.yaml"
HOSTNAME_DARWIN="pane"
VM_SERVICE="system/org.nixos.nixos-vm-based-linux-builder"
CACHE_HOST="nix.work-cache.net"
CACHE_PROBE_PATH="/nix-cache/nix-cache-info"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

log() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

[[ -d "$REPO" ]] || die "repo not found at $REPO"
command -v nix >/dev/null || die "nix not on PATH"
command -v darwin-rebuild >/dev/null || die "darwin-rebuild not on PATH"

# Run age/sops/ssh-to-age out of an ephemeral nix shell so this script
# works even before they land in the home-manager profile.
NIX_RUN=(nix shell --quiet nixpkgs#age nixpkgs#sops nixpkgs#mkpasswd --command)

log "step 1/6: ensure age key exists at $AGE_KEY"
mkdir -p "$AGE_DIR"
chmod 700 "$AGE_DIR"

# Migration: an earlier version of this script staged the key inside the
# flake at .secrets/age.key (with the CLI path as a symlink). Revert to a
# real file at the standard sops location so nothing secret-adjacent lives
# in the repo.
LEGACY_KEY="${REPO}/.secrets/age.key"
if [[ -L "$AGE_KEY" ]]; then
  target="$(readlink "$AGE_KEY")"
  if [[ "$target" == "$LEGACY_KEY" && -f "$LEGACY_KEY" ]]; then
    log "  migrating key from $LEGACY_KEY back to $AGE_KEY"
    rm "$AGE_KEY"
    mv "$LEGACY_KEY" "$AGE_KEY"
    rmdir "${REPO}/.secrets" 2>/dev/null || true
  fi
fi

if [[ ! -f "$AGE_KEY" || $FORCE -eq 1 ]]; then
  if [[ -f "$AGE_KEY" && $FORCE -eq 1 ]]; then
    backup="${AGE_KEY}.bak.$(date +%s)"
    cp "$AGE_KEY" "$backup"
    log "  --force: backed up existing key to $backup"
  fi
  "${NIX_RUN[@]}" age-keygen -o "$AGE_KEY"
  chmod 600 "$AGE_KEY"
else
  log "  age key already present (use --force to rotate)"
fi

RECIPIENT="$("${NIX_RUN[@]}" age-keygen -y "$AGE_KEY")"
log "  recipient: $RECIPIENT"

log "step 2/6: write $SOPS_POLICY"
if [[ ! -f "$SOPS_POLICY" || $FORCE -eq 1 ]]; then
  cat > "$SOPS_POLICY" <<EOF
# Generated by scripts/bootstrap-sops-builder.sh
creation_rules:
  - path_regex: secrets\.yaml$
    age: ${RECIPIENT}
EOF
else
  log "  policy exists; not overwriting"
fi

log "step 3/6: encrypt secrets into $SECRETS_FILE"
# Treat zero-byte, non-sops-formatted, or partial files as missing. A
# prior run can leave an empty SECRETS_FILE behind if `>` creates the
# file before the encrypt command errors out. We also re-encrypt if any
# of the expected keys is absent in the encrypted document.
needs_secret=0
required_keys=(tailscale-authkey it-admin-password-hash)
if [[ ! -s "$SECRETS_FILE" ]]; then
  needs_secret=1
  [[ -f "$SECRETS_FILE" ]] && log "  existing $SECRETS_FILE is empty; regenerating"
elif ! grep -q '^sops:' "$SECRETS_FILE" 2>/dev/null; then
  needs_secret=1
  log "  existing $SECRETS_FILE missing sops metadata; regenerating"
else
  for k in "${required_keys[@]}"; do
    if ! grep -q "^${k}:" "$SECRETS_FILE"; then
      needs_secret=1
      log "  existing $SECRETS_FILE missing key '${k}'; regenerating"
      break
    fi
  done
fi
[[ $FORCE -eq 1 ]] && needs_secret=1

if [[ $needs_secret -eq 1 ]]; then
  echo
  echo "Generate a reusable + ephemeral Tailscale pre-auth key (tag:builder"
  echo "or whatever ACL grants tailnet access) at:"
  echo "  https://login.tailscale.com/admin/settings/keys"
  echo
  printf 'Paste Tailscale auth key (tskey-auth-...): '
  IFS= read -rs TS_AUTHKEY
  echo
  [[ "$TS_AUTHKEY" == tskey-auth-* ]] \
    || die "key did not start with tskey-auth-, aborting"

  echo
  echo "Set a password for the 'it-admin' user in the linux-builder VM."
  echo "Used for console / recovery; routine SSH access uses the host key."
  while :; do
    printf 'it-admin password: '
    IFS= read -rs IT_ADMIN_PW
    echo
    printf 'it-admin password (confirm): '
    IFS= read -rs IT_ADMIN_PW2
    echo
    [[ -n "$IT_ADMIN_PW" ]] || { echo "  empty password not allowed"; continue; }
    [[ "$IT_ADMIN_PW" == "$IT_ADMIN_PW2" ]] && break
    echo "  passwords do not match, try again"
  done
  unset IT_ADMIN_PW2

  # mkpasswd -m sha-512 yields a $6$ hash compatible with NixOS's
  # users.users.<name>.hashedPasswordFile.
  IT_ADMIN_HASH="$(printf '%s' "$IT_ADMIN_PW" | "${NIX_RUN[@]}" mkpasswd -m sha-512 -s)"
  unset IT_ADMIN_PW
  [[ "$IT_ADMIN_HASH" == \$6\$* ]] \
    || die "mkpasswd did not produce a sha-512 hash"

  # sops matches creation_rules against the INPUT path, so the temp
  # plaintext file must be named secrets.yaml. Use a private dir under
  # the user's home so /tmp permissions don't leak the plaintext.
  TMPDIR_SECRET="$(mktemp -d "${TMPDIR:-/tmp}/sops-bootstrap.XXXXXX")"
  chmod 700 "$TMPDIR_SECRET"
  TMP="$TMPDIR_SECRET/secrets.yaml"
  OUT="$TMPDIR_SECRET/secrets.enc.yaml"
  trap 'rm -rf "$TMPDIR_SECRET"' EXIT
  # Quote the hash because it contains $ and / characters; YAML scalar
  # rules accept single-quoted strings with no escape processing.
  {
    printf 'tailscale-authkey: %s\n' "$TS_AUTHKEY"
    printf "it-admin-password-hash: '%s'\n" "$IT_ADMIN_HASH"
  } > "$TMP"
  chmod 600 "$TMP"
  unset TS_AUTHKEY IT_ADMIN_HASH

  # Encrypt to a temp file first, then move into place — avoids leaving
  # an empty SECRETS_FILE behind if sops errors mid-run. Pass --config
  # explicitly since sops resolves .sops.yaml relative to the input file.
  "${NIX_RUN[@]}" sops --config "$SOPS_POLICY" --encrypt \
      --input-type yaml --output-type yaml "$TMP" > "$OUT"
  [[ -s "$OUT" ]] && grep -q '^sops:' "$OUT" \
    || die "sops produced empty/invalid output; aborting"
  mv "$OUT" "$SECRETS_FILE"

  rm -rf "$TMPDIR_SECRET"
  trap - EXIT
else
  log "  $SECRETS_FILE already encrypted with all required keys; skipping (use --force to rotate)"
fi

# Determinate's flake evaluation only sees files that git knows about
# (tracked or staged). Untracked files in the working tree are filtered
# out even though the tree is "dirty". Stage the encrypted secret and
# policy so they're visible in the in-memory git snapshot Nix builds.
# Both files are safe to commit: secrets.yaml is age-encrypted, .sops.yaml
# only contains the public recipient.
log "  staging $SOPS_POLICY and $SECRETS_FILE so Nix can see them"
( cd "$REPO" && git add .sops.yaml secrets.yaml )

log "step 4/6: update flake lock for sops-nix"
# `nix flake update <input>` is the non-deprecated form for refreshing a
# single input on modern Nix; fall back to full update on older Nix.
( cd "$REPO" && nix flake update sops-nix 2>/dev/null ) \
  || ( cd "$REPO" && nix flake update )

log "step 5/6: darwin-rebuild switch (--impure to import the host age key)"
# --impure is required because environment.etc.<name>.source references
# an absolute path outside the flake (/Users/.../sops/age/keys.txt).
# All other inputs are pinned; the impurity is limited to that one file.
( cd "$REPO" && sudo darwin-rebuild switch --impure \
    --flake ".#${HOSTNAME_DARWIN}" )

log "step 6/6: restart linux-builder VM and verify"
sudo launchctl kickstart -k "$VM_SERVICE"

# Give the VM time to boot, tailscaled to auth, MagicDNS to settle.
log "  waiting up to 60s for tailscaled inside VM..."
for i in $(seq 1 12); do
  if sudo ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 \
       -i /etc/nix/builder_ed25519 builder@nixos-vm-based-linux-builder \
       'tailscale status >/dev/null 2>&1 && \
        curl -fsSI -o /dev/null --max-time 5 https://'"${CACHE_HOST}${CACHE_PROBE_PATH}"'' \
       2>/dev/null; then
    log "  cache reachable from VM"
    log "done."
    exit 0
  fi
  sleep 5
done

cat >&2 <<EOF
[warn] could not reach https://${CACHE_HOST}${CACHE_PROBE_PATH} from the VM
       within 60s. Inspect with:

  sudo ssh -i /etc/nix/builder_ed25519 it-admin@nixos-vm-based-linux-builder \\
    'sudo journalctl -u tailscaled -u tailscaled-autoconnect -n 80 --no-pager; \\
     sudo ls -la /run/secrets /run/secrets-for-users; \\
     tailscale status; getent hosts ${CACHE_HOST}'

Possible causes:
  - Tailscale pre-auth key expired or wrong tag/ACL
  - VM has no outbound to login.tailscale.com via host NAT
  - ACL on tailnet does not permit tag:builder -> cache host
EOF
exit 1
