#!/usr/bin/env bash
# -*- bash -*-
# Local Variables:
# mode: shell-script
# sh-shell: bash
# End:

# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

# shellcheck disable=1090
source ~/.profile

# add guix to env
if [ -d "$HOME/.guix-profile" ]; then
  GUIX_PROFILE="$HOME/.guix-profile"
  source "${GUIX_PROFILE}/etc/profile"
fi
if [ -d "${HOME}/.config/guix" ]; then
  GUIX_PROFILE="${HOME}/.config/guix/current"
  . "$GUIX_PROFILE/etc/profile"
fi

# source the file if the provided FILE exists
function src_exists() {
    local fpath="$1"
    if [ -f "${fpath}" ]; then
      # shellcheck disable=SC1090
      source "${fpath}"
    fi
}

# prepend to PATH if the provided DIR exists
function ppath_exists() {
    local path_dir="$1"
    if [ -d "${path_dir}" ]; then
        export PATH="${path_dir}:${PATH}"
    fi
}

# append to PATH if the provided DIR exists
function apath_exists() {
    local path_dir="$1"
    if [ -d "${path_dir}" ]; then
        export PATH="${PATH}:${path_dir}"
    fi
}

# Source custom env installations
src_exists "~/v/bin/activate"
src_exists "~/.ghcup/env"
src_exists "~/.rye/env"
src_exists "~/.cargo/env" # TODO: might not actually want this
src_exists "~/.grit/bin/env"
src_exists "~/.elan/env"

# add .local/bin to path
ppath_exists "${HOME}/.local/bin"
# add doom emacs to path
ppath_exists "${HOME}/.config/emacs/bin"
# add cargo bins to path
ppath_exists "${HOME}/.cargo/bin"
# add deno to path
ppath_exists "${HOME}/.deno/bin"

# add shell hooks
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi
if command -v direnv &> /dev/null; then
  eval "$(direnv hook bash)"
fi
if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi

# add all bash completions for guix-installed programs
for file in ~/.guix-profile/etc/bash_completion.d/* ~/.guix-profile/share/bash-completion/completions/*; do
  # shellcheck disable=SC1090
  [ -r "${file}" ] && . "${file}"
done


##
## One-off support for things
##
if [ -d "${HOME}/.deno" ]; then
  export DENO_INSTALL="${HOME}/.deno"
fi


# asni seq to reset color
alias fix-color='echo -ne "\033[0m"'

HISTFILESIZE=100000
HISTSIZE=10000

shopt -s histappend
shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s checkjobs
